services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    command: "sh entrypoint.sh"
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - .:/app/

  postgres:
    image: postgres:15-alpine
    container_name: example-db
    ports:
    - "${POSTGRES_PORT}:5432"
    env_file:
    - ./.env
    


volumes:
  postgres_data: